aerogear/aerogear-parent

aerogear-bom/pom.xml

latest apns version

---

aerogear-bom/pom.xml

We now have a final version of 1.1.0
Tested with UPS master and deployed on WF 8.2 -> works fine

updating KC version to latest

---

aerogear-android-bom/pom.xml
aerogear-bom/pom.xml
aerogear-test-bom/pom.xml
pom.xml

Upgrading to 1.0.0.Beta.6, done for [AGPUSH-1259](https://issues.jboss.org/browse/AGPUSH-1259)

using latest version of java-apns 

---

aerogear-test-bom/pom.xml

update of Arquillian Rule to 0.3.0

---

aerogear-test-bom/pom.xml

update to Arquillian Spacelift 1.0.0.Alpha6

---

aerogear-test-bom/pom.xml

update of non deploying container to 0.4.0

---

aerogear-test-bom/pom.xml

@kpiwko @matzew 
I am thinking what else should be updated by this being merged ... ups int tests maybe?

update to Arquillian 1.1.7.Final

---

aerogear-test-bom/pom.xml

@kpiwko @abstractj @matzew 
it would be nice to have it merged and used with parent which will be used in ups beta 2

arquillian bumps

---

aerogear-bom/pom.xml

Latest of KC (1.3.0 is actually broken) 
1.3.1 will be out tomorrow

Using KC 1.3.1

---

.travis.yml
pom.xml

Updates to use JDK 7
@secondsun @danielpassos might be handy for AGDROID too

removing outdated JDK

---

aerogear-bom/pom.xml

See: https://issues.jboss.org/browse/AGPUSH-1539

Update to Keycloak 1.5.x

---

aerogear-bom/pom.xml

See: https://issues.jboss.org/browse/AGPUSH-1528

Update UPS to Keycloak 1.7.0.Final

---

aerogear-bom/pom.xml

Using latest of Jackson

---

.gitignore
.travis.yml
aerogear-android-bom/pom.xml
aerogear-bom/pom.xml
aerogear-test-bom/pom.xml
aerogear-unifiedpush-bom/pom.xml
pom.xml

@danielpassos @secondsun @danbev  can you take a look ? 
First attempt to make the bom more modern, e.g. defaulting to java8 and latest plugin versions

Major updates

---

aerogear-android-sdk-bom/pom.xml

See: [AGDROID-714](https://issues.jboss.org/browse/AGDROID-714) - Move all aerogear-android-sdk dependencies to bom

Added Android libraries

---

aerogear-android-sdk-bom/pom.xml

Adding the `jose4j` dependency for the auth module in the SDK.

[WIP] AGDROID-686 Add additional depenencies for auth module

---

aerogear-android-sdk-bom/pom.xml

Going to revert it to apply the 1.1.9 release commits

Revert "add json dependency, required for certain unit test scenarios"

---

aerogear-android-sdk-bom/pom.xml

Requested by @secondsun to add dependencies to the bom as part of PR [#69](https://github.com/aerogear/aerogear-android-sdk/pull/69)
Added two dependencies to the bom customtabs and rootbeer lib

Added dependencies for self defense checks

---

aerogear-android-sdk-bom/pom.xml

Add dependency for okhttp mockwebserver used to test the http module

add okhttp mockwebserver dependency

---

aerogear-unifiedpush-bom/pom.xml

This PR updates many of the dependencies for aerogear projects, most notable UPS.
Set the aerogear-parent version in your project to 1.1.3-SNAPSHOT and ensure it compiles
- [ x ] Code has been tested locally by PR requester
Check this PR in aerogear-unifiedpush-server for more details. https://github.com/aerogear/aerogear-unifiedpush-server/pull/1013

Updating dependencies 

---

aerogear-unifiedpush-bom/pom.xml

This PR includes updates for more components

updating jax-rs
